WebApplication/Models/BuyProduct.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApplication.Models
{
    public class BuyProduct
    {
        public string MainStockID { get; set; }
        public Nullable<long> ProductID { get; set; }
        public string unitType { get; set; }
        public float NumInOne { get; set; }
        public Nullable<double> BuyingCost { get; set; }
        public Nullable<double> transCost { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<double> TotalCost { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<double> SellingPriceUSD { get; set; }
        public string PrdNameEng { get; set; }
        public string barCode { get; set; }
        public string OrderComment { get; set; }
        public string PrdCategory { get; set; }
        public Nullable<double> Val { get; set; }
        public string Type { get; set; }
        public string BuyID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string InvoiceNo { get; set; }
        public string SupplierID { get; set; }
        public string CompanyName { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<double> PerDis { get; set; }
        public Nullable<double> AmtDis { get; set; }
        public Nullable<double> GrandTotal { get; set; }
        public Nullable<double> AmtPay { get; set; }
        public Nullable<double> AmtLoan { get; set; }
        public string Username { get; set; }
        public Nullable<double> usdtoKher { get; set; }
        public Nullable<double> usdtoTHB { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> DateReturn { get; set; }
        public string Description { get; set; }
        public string StockID { get; set; }

    }
}

WebApplication/Controllers/BuyProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication.Models;
using WebApplication.Repositories;
using WebApplication.Helpers;

namespace WebApplication.Controllers
{
    [Authorize]
    public class BuyProductController : Controller
    {
        private DataContext context;
        private BuyProductRepository buyProductRepository;
        private SupplierRepository supplierRepository;
        public BuyProductController()
        {
            this.context = new DataContext();
            this.buyProductRepository = new BuyProductRepository();
            this.supplierRepository = new SupplierRepository();
        }
        // GET: BuyProduct
        public ActionResult Index()
        {
            DropDownListFor();
            return View();
        }
        public ActionResult GetData(BaseDatatable param)
        {
            var data = buyProductRepository.GetForDataTable();
            if (!string.IsNullOrEmpty(param.sSearch) &&
                !string.IsNullOrWhiteSpace(param.sSearch))
            {
                data = data.Where(x => x.InvoiceNo.Contains(param.sSearch)).ToList();
            }
            //Block show column
            var sortColumnIndex = HttpContext.Request.QueryString["iSortCol_0"];
            var sortDirection = HttpContext.Request.QueryString["sSortDir_0"];
            data = buyProductRepository.SortByColumnWithOrder(sortColumnIndex, sortDirection, data);

            var displayResult = data.Skip(param.iDisplayStart)
                                .Take(param.iDisplayLength).ToList();
            var totalRecords = data.Count();
            return Json(new
            {
                param.sEcho,
                iTotalRecords = totalRecords,
                iTotalDisplayRecords = totalRecords,
                aaData = displayResult
            }, JsonRequestBehavior.AllowGet);
        }
        //GET:BuyProduct/GetMainStockOrdering
        public ActionResult GetMainStockOrdering(BaseDatatable param)
        {
            string buyId = Request["buyId"] ?? "0";
            var data = buyProductRepository.GetForMainStockOrdering(buyId);
            if (!string.IsNullOrEmpty(param.sSearch) &&
                !string.IsNullOrWhiteSpace(param.sSearch))
            {
                data = data.Where(x => x.PrdNameEng.Contains(param.sSearch)).ToList();
            }
            //Block show column
            var sortColumnIndex = HttpContext.Request.QueryString["iSortCol_0"];
            var sortDirection = HttpContext.Request.QueryString["sSortDir_0"];
            data = buyProductRepository.SortByColumnWithOrdering(sortColumnIndex, sortDirection, data);

            var displayResult = data.Skip(param.iDisplayStart)
                                .Take(param.iDisplayLength).ToList();
            var totalRecords = data.Count();
            return Json(new
            {
                param.sEcho,
                iTotalRecords = totalRecords,
                iTotalDisplayRecords = totalRecords,
                aaData = displayResult
            }, JsonRequestBehavior.AllowGet);
        }
        // GET: BuyProduct/AddOrder
        [Route("BuyProduct/AddOrder")]
        [HttpPost]
        public JsonResult AddOrder(MainStock data)
        {
            var mainStock = context.tbl_mainstock_ordering
                .Any(x => x.ProductID == data.ProductID 
                && x.UserID == IUser.Id
                && x.BuyID == data.BuyID
                && x.BuyStatus == "New");
            if (mainStock)
            {
                return Json(buyProductRepository.Update(data), JsonRequestBehavior.AllowGet);
            }
            return Json(buyProductRepository.Create(data), JsonRequestBehavior.AllowGet);
        }
        // GET: BuyProduct/Delete/5
        [Route("BuyProduct/Delete")]
        [HttpPost]
        public JsonResult Delete(MainStock data)
        {
            return Json(buyProductRepository.Delete(data), JsonRequestBehavior.AllowGet);
        }
        // GET: BuyProduct/Create
        public ActionResult Create()
        {
            ViewBag.InvoiceNo = "";
            ViewBag.buyId = "0";
            DropDownListFor();
            return View();
        }
        // POST: BuyProduct/Create
        [HttpPost]
        public ActionResult Create(tbl_BuyProducts data)
        {
            try
            {
                bool hasItem = context.tbl_mainstock_ordering.Any(x => x.BuyID == data.BuyID);
                if (!hasItem)
                {
                    TempData["flashError"] = "The payment was error invalid data, try again.";
                    if(data.BuyID == "0")
                    {
                        return RedirectToAction("Create");
                    }
                    return RedirectToAction("Edit", new { slug = data.BuyID });
                }
                //update payment to supplier
                if (data.BuyID != "0")
                {
                    buyProductRepository.UpdatePayment(data);
                    TempData["flashSuccess"] = "The payment was successfully updated.";
                    return RedirectToAction("Index");
                }
                //create payment to supplier
                bool hasInvoiceNo = context.tbl_BuyProducts.Any(x => x.InvoiceNo == data.InvoiceNo);
                if (hasInvoiceNo)
                {
                    TempData["flashError"] = "You've already entered that invoice number, try again.";
                    return RedirectToAction("Create");
                }
                buyProductRepository.CreatePayment(data);
                TempData["flashSuccess"] = "The payment was successfully created.";
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        [HttpPost]
        public JsonResult TransferToModify(MainStock data)
        {
            return Json(new { status = buyProductRepository.TransferToModify(data), message = "" }, JsonRequestBehavior.AllowGet);
        }
        // GET: BuyProduct/Edit
        public ActionResult Edit(string slug)
        {
            var buyProduct = context.tbl_BuyProducts.FirstOrDefault(x => x.BuyID == slug);
            ViewBag.InvoiceNo = buyProduct.InvoiceNo;
            ViewBag.buyId = slug;
            DropDownListFor();
            return View();
        }
        // GET: BuyProduct/BuyDetail
        public ActionResult BuyDetail(string slug)
        {
            ViewBag.buyId = slug;
            return View();
        }
        // GET: BuyProduct/GetDataBuyDetail
        public ActionResult GetDataBuyDetail(BaseDatatable param)
        {
            string buyId = Request["buyId"];
            var data = buyProductRepository.GetDataBuyDetail(buyId);
            if (!string.IsNullOrEmpty(param.sSearch) &&
                !string.IsNullOrWhiteSpace(param.sSearch))
            {
                data = data.Where(x => x.PrdNameEng.Contains(param.sSearch)).ToList();
            }
            //Block show column
            var sortColumnIndex = HttpContext.Request.QueryString["iSortCol_0"];
            var sortDirection = HttpContext.Request.QueryString["sSortDir_0"];
            data = buyProductRepository.SortByColumnWithOrdering(sortColumnIndex, sortDirection, data);

            var displayResult = data.Skip(param.iDisplayStart)
                                .Take(param.iDisplayLength).ToList();
            var totalRecords = data.Count();
            return Json(new
            {
                param.sEcho,
                iTotalRecords = totalRecords,
                iTotalDisplayRecords = totalRecords,
                aaData = displayResult
            }, JsonRequestBehavior.AllowGet);
        }
        // POST: Customer/CreateSupplier
        [Route("Customer/CreateSupplier")]
        [HttpPost]
        public ActionResult CreateSupplier(Supplier data)
        {
            bool supplier = context.tbl_suppliers.Any(x => x.CompanyName == data.CompanyName);
            if (supplier)
            {
                TempData["flashError"] = "The supplier was error created, try again.";
                return RedirectToAction("Create");
            }

            supplierRepository.Create(data);
            TempData["flashSuccess"] = "The supplier was successfully created.";
            return RedirectToAction("Create");
        }
        public void DropDownListFor()
        {
            var stockTypes = context.tblStockTypes.ToList();
            ViewBag.StockTypes = new SelectList(stockTypes, "StockID", "StockName");

            var suppliers = context.tbl_suppliers.ToList();
            ViewBag.Suppliers = new SelectList(suppliers, "SupplierID", "CompanyName");
        }
    }
}

WebApplication/Views/BuyProduct/BuyDetail.cshtml
@model IEnumerable<WebApplication.Models.BuyProduct>
@section Styles {
    <link href="~/assets/plugins/datatables-bs4/css/dataTables.bootstrap4.css" rel="stylesheet" />
    <link href="~/assets/plugins/datatables-responsive/css/responsive.bootstrap4.css" rel="stylesheet">
}
<div class="card">
    <div class="card-header">
        <div class="d-flex justify-content-between">
            <div class="card-title align-self-center">
                @Resources.BuyProduct.BuyDetail
            </div>
            <div>
                <a href="@Url.Action("Create", "BuyProduct")" class="btn btn-min btn-outline-primary">
                    <i class="fa fa-plus-circle"></i>
                    BuyProduct
                </a>
            </div>
        </div>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-sm-12">
                <table class="table table-hover table-sm data-table dt-responsive nowrap" style="width: 100%">
                    <thead>
                        <tr>
                            <th>@Resources.Globle.No</th>
                            <th>@Resources.BuyProduct.Date</th>
                            <th>@Resources.BuyProduct.InvoiceNo</th>
                            <th>@Resources.BuyProduct.Supplier</th>
                            <th>@Resources.BuyProduct.PrdNameEng</th>
                            <th>@Resources.BuyProduct.barCode</th>
                            <th>@Resources.BuyProduct.UnitType</th>
                            <th>@Resources.BuyProduct.Quantity</th>
                            <th>@Resources.BuyProduct.BuyingCost</th>
                            <th>@Resources.BuyProduct.TotalCost</th>
                            <th>@Resources.BuyProduct.totalInStock</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
</div>
@section Scripts {
    <script src="~/assets/plugins/datatables/jquery.dataTables.js"></script>
    <script src="~/assets/plugins/datatables-bs4/js/dataTables.bootstrap4.js"></script>
    <script src="~/assets/plugins/datatables-responsive/js/dataTables.responsive.js"></script>
    <script src="~/assets/plugins/datatables-responsive/js/responsive.bootstrap4.js"></script>
    <script src="~/assets/plugins/moment/moment.min.js"></script>
    <script type="text/javascript">
        var sidebarCollapse = $('#sidebarCollapse');
        $(function () {
            sidebarCollapse.addClass("sidebar-collapse");
            var dataTable = $('.data-table')
                .DataTable({
                    sAjaxSource: '@Url.Action("GetDataBuyDetail", "BuyProduct")',
                    fnServerParams: function (aoData) {
                        aoData.push({ "name": "buyId", "value": @ViewBag.buyId });
                    },
                    order: [[2, 'desc']],
                    bServerSide: true,
                    pageLength: 25,
                    bProcessing: true,
                    bSearchable: true,
                    columns: [
                        {
                            data: null, sortable: false,
                            render: function (data, type, row, meta) {
                                return meta.row + meta.settings._iDisplayStart + 1;
                            }
                        },
                        { data: "Date", autoWidth: true, searchable: true },
                        { data: "InvoiceNo", searchable: true, sortable: false },
                        { data: "CompanyName", sortable: false },
                        { data: "PrdNameEng", sortable: false },
                        { data: "barCode", sortable: false },
                        { data: "unitType", sortable: false },
                        { data: "Quantity", sortable: false },
                        { data: "BuyingCost", sortable: false, render: $.fn.dataTable.render.number(',', '.', 2, '$') },
                        { data: "TotalCost", sortable: false, render: $.fn.dataTable.render.number(',', '.', 2, '$') },
                        { data: "totalInStock", sortable: false },
                    ],
                    columnDefs: [
                        {
                            targets: [1],
                            render: function (data, type, row, meta) {
                                return moment(data).format('YYYY-MM-DD');
                            }
                        }
                    ],
                });
            });
    </script>
}

WebApplication/Views/BuyProduct/Index.cshtml
@model IEnumerable<WebApplication.Models.BuyProduct>
@section Styles {
    <link href="~/assets/plugins/datatables-bs4/css/dataTables.bootstrap4.css" rel="stylesheet" />
    <link href="~/assets/plugins/datatables-responsive/css/responsive.bootstrap4.css" rel="stylesheet">
}
<div class="card">
    <div class="card-header">
        <div class="d-flex justify-content-between">
            <div class="card-title align-self-center">
                @Resources.BuyProduct.Title
            </div>
            <div>
                <a href="@Url.Action("Create", "BuyProduct")" class="btn btn-min btn-primary">
                    <i class="fa fa-plus-circle"></i>
                    @Resources.Buttons.Create
                </a>
            </div>
        </div>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-sm-12">
                <table class="table table-hover table-sm data-table nowrap" style="width: 100%">
                    <thead>
                        <tr>
                            <th>@Resources.Globle.No</th>
                            <th>@Resources.BuyProduct.Date</th>
                            <th>@Resources.BuyProduct.InvoiceNo</th>
                            <th>@Resources.BuyProduct.Supplier</th>
                            <th>@Resources.BuyProduct.Total</th>
                            <th>@Resources.BuyProduct.AmtDis</th>
                            <th>@Resources.BuyProduct.GrandTotal</th>
                            <th>@Resources.BuyProduct.AmtPay</th>
                            <th>@Resources.BuyProduct.AmtLoan</th>
                            <th>@Resources.BuyProduct.Username</th>
                            @*<th>@Resources.BuyProduct.Description</th>*@
                            <th>@Resources.Globle.Actions</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
</div>
@section Scripts {
    <script src="~/assets/plugins/datatables/jquery.dataTables.js"></script>
    <script src="~/assets/plugins/datatables-bs4/js/dataTables.bootstrap4.js"></script>
    <script src="~/assets/plugins/datatables-responsive/js/dataTables.responsive.js"></script>
    <script src="~/assets/plugins/datatables-responsive/js/responsive.bootstrap4.js"></script>
    <script src="~/assets/plugins/moment/moment.min.js"></script>
    <script type="text/javascript">
        var sidebarCollapse = $('#sidebarCollapse');
        $(function () {
            //sidebarCollapse.addClass("sidebar-collapse");
            $(document).on('click', '.btnDetail', function () {
                var id = $(this).data('id');
                window.location.href = '@Url.Action("BuyDetail", "BuyProduct")?slug=' + id;
            });
            $(document).on('click', '.btnTranferToModify', function () {
                var _this = $(this);
                var id = _this.data('id');
                _this.prop('disabled', true);
                _this.find('span').removeClass('d-none');
                var data = {};
                data.BuyID = id;
                $.ajax({
                    url: "@Url.Action("TransferToModify", "BuyProduct")",
                    type: "POST",
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(data),
                    dataType: "json",
                    processData: false,
                    success: function (res) {
                        if (res.status == 'True') {
                            window.location.href = '@Url.Action("Edit", "BuyProduct")?slug=' + id;
                        } else {
                            _this.prop('disabled', false);
                            _this.find('span').addClass('d-none');
                        }
                    },
                    error: function (message) {
                        _this.prop('disabled', false);
                        _this.find('span').addClass('d-none');
                        console.log(message);
                    }
                });
            });
            var dataTable = $('.data-table')
                .DataTable({
                    sAjaxSource: '@Url.Action("GetData", "BuyProduct")',
                    order: [[2, 'desc']],
                    bServerSide: true,
                    pageLength: 25,
                    bProcessing: true,
                    bSearchable: true,
                    scrollX: true,
                    columns: [
                        {
                            data: null, sortable: false,
                            render: function (data, type, row, meta) {
                                return meta.row + meta.settings._iDisplayStart + 1;
                            }
                        },
                        { data: "Date", autoWidth: true, searchable: true },
                        { data: "InvoiceNo", searchable: true, sortable: false },
                        { data: "CompanyName", sortable: false },
                        { data: "Total", sortable: false, render: $.fn.dataTable.render.number(',', '.', 2, '$') },
                        //{ data: "PerDis", sortable: false },
                        { data: "AmtDis", sortable: false, render: $.fn.dataTable.render.number(',', '.', 2, '$') },
                        { data: "GrandTotal", sortable: false, render: $.fn.dataTable.render.number(',', '.', 2, '$') },
                        { data: "AmtPay", sortable: false, render: $.fn.dataTable.render.number(',', '.', 2, '$') },
                        { data: "AmtLoan", sortable: false, render: $.fn.dataTable.render.number(',', '.', 2, '$') },
                        { data: "Username", sortable: false },
                        //{ data: "Description", sortable: false },
                        {
                            data: "BuyID",
                            sortable: false,
                            render: function (data, type, full, meta) {
                                var actions = '<button type="button" data-id="' + data + '" class="btn btnTranferToModify btn-sm btn-primary mx-1"><span class="spinner-border spinner-border-sm d-none mr-2" role="status" aria-hidden="true"></span>Edit</a>';
                                    actions += '<button type="button" data-id="' + data + '" class="btn btnDetail btn-sm btn-primary mx-1">Detail</a>';
                                return actions;
                            }
                        }
                    ],
                    columnDefs: [
                        {
                            targets: [1],
                            render: function (data, type, row, meta) {
                                return moment(data).format('YYYY-MM-DD hh:mm a');
                            }
                        }
                    ],
                });
            });
    </script>
}