WebApplication/Controllers/AppSettingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication.Models;
using WebApplication.Repositories;

namespace WebApplication.Controllers
{
    [Authorize(Roles = "SuperAdmin")]
    public class AppSettingController : BaseController
    {
        private DataContext _context;
        private AppSettingRepository _appSettingRepository;
        public AppSettingController()
        {
            this._context = new DataContext();
            this._appSettingRepository = new AppSettingRepository();
        }
        // GET: AppSetting
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult GetData(BaseDatatable param)
        {
            var data = _appSettingRepository.GetForDataTable();
            if (!string.IsNullOrEmpty(param.sSearch) &&
                !string.IsNullOrWhiteSpace(param.sSearch))
            {
                data = data.Where(x => x.Name.ToLower().Contains(param.sSearch.ToLower())).ToList();
            }
            var sortColumnIndex = HttpContext.Request.QueryString["iSortCol_0"];
            var sortDirection = HttpContext.Request.QueryString["sSortDir_0"];
            data = _appSettingRepository.SortByColumnWithOrder(sortColumnIndex, sortDirection, data);

            var displayResult = data.Skip(param.iDisplayStart)
                                .Take(param.iDisplayLength).ToList();
            var totalRecords = data.Count();
            return Json(new
            {
                param.sEcho,
                iTotalRecords = totalRecords,
                iTotalDisplayRecords = totalRecords,
                aaData = displayResult
            }, JsonRequestBehavior.AllowGet);
        }
        // POST: AppSetting/Edit/5
        [Route("AppSetting/Edit")]
        [HttpPost]
        public JsonResult Edit(tbl_APP_Setting data)
        {
            var appSetting = _context.tbl_APP_Setting.Where(x => x.Name == data.Name).FirstOrDefault();
            tbl_APP_Setting _AppSetting = new tbl_APP_Setting();
            _AppSetting.Name = appSetting.Name;
            _AppSetting.Value = appSetting.Value;
            _AppSetting.Description = appSetting.Description;
            return Json(_AppSetting, JsonRequestBehavior.AllowGet);
        }
        //// POST: AppSetting/Update
        //[Route("AppSetting/Update")]
        //[HttpPost]
        //public JsonResult Update(tbl_APP_Setting data)
        //{
        //    //return Json(data.Value, JsonRequestBehavior.AllowGet);
        //    return Json(_appSettingRepository.Update(data), JsonRequestBehavior.AllowGet);
        //}
    }
}

WebApplication/Views/AppSetting/Partials/_CreateOrUpdate.cshtml
@model WebApplication.Models.tbl_App_Setting
@using (Html.BeginForm("Update", "AppSetting", FormMethod.Post))
{
    <div class="modal fade" id="modal-form">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h6 id="modal-title" class="modal-title text-secondary">
                        <i class="fa fa-plus-circle"></i>
                        @Resources.Globle.Edit
                    </h6>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">

                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="row">
                        <div class="col">
                            <div class="form-group">
                                @Html.Label("កំណត់", htmlAttributes: new { @class = "control-label" })
                                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @readonly = "True" } })
                                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                @Html.Label("តម្លៃ", htmlAttributes: new { @class = "control-label" })
                                @Html.EditorFor(model => model.Value, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Value, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                @Html.Label("ចំណាំ", htmlAttributes: new { @class = "control-label" })
                                @Html.EditorFor(model => model.Note, new { htmlAttributes = new { @class = "form-control", @placeholder = "ចំណាំ" } })
                                @Html.ValidationMessageFor(model => model.Note, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer justify-content-between">
                    <button type="button" class="btn btn-danger btn-min" data-dismiss="modal">
                        <i class="fa fa-times-circle" aria-hidden="true"></i>
                        @Resources.Globle.Cancel
                    </button>
                    <button type="submit" id="btnSaveOrUpdate" class="btn btn-success btn-min">
                        <i class="far fa-check-circle"></i>
                        @Resources.Globle.Update
                    </button>
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>
    <!-- /.modal -->
}