WebApplication/Controllers/ProductPackageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication.Models;
using WebApplication.Repositories;

namespace WebApplication.Controllers
{
    [Authorize]
    public class ProductPackageController : Controller
    {
        private DataContext context;
        private ProductPackageRepository productPackageRepository;
        public ProductPackageController()
        {
            this.context = new DataContext();
            this.productPackageRepository = new ProductPackageRepository();
        }
        // GET: ProductPackage
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult GetData(BaseDatatable param)
        {
            //string paraId = Request["PrdCategID"];
            var data = productPackageRepository.GetForDataTable();
            if (!string.IsNullOrEmpty(param.sSearch) &&
                !string.IsNullOrWhiteSpace(param.sSearch))
            {
                data = data.Where(x => x.Product_Package.ToLower().Contains(param.sSearch.ToLower())).ToList();
            }
            var sortColumnIndex = HttpContext.Request.QueryString["iSortCol_0"];
            var sortDirection = HttpContext.Request.QueryString["sSortDir_0"];
            data = productPackageRepository.SortByColumnWithOrder(sortColumnIndex, sortDirection, data);

            var displayResult = data.Skip(param.iDisplayStart)
                                .Take(param.iDisplayLength).ToList();
            var totalRecords = data.Count();
            return Json(new
            {
                param.sEcho,
                iTotalRecords = totalRecords,
                iTotalDisplayRecords = totalRecords,
                aaData = displayResult
            }, JsonRequestBehavior.AllowGet);
        }
        // POST: ProductPackage/Create
        [Route("ProductPackage/Create")]
        [HttpPost]
        public JsonResult Create(tbl_products_Package data)
        {
            if (data.Product_PackageID != 0)
            {
                var resUpdate = productPackageRepository.Update(data);
                return Json(new { resUpdate.status, resUpdate.message }, JsonRequestBehavior.AllowGet);
            }
            bool packageName = context.tbl_products_Package.Any(x => x.Product_Package == data.Product_Package);
            if (packageName)
            {
                return Json(new { status = "Warning", message = "Your\'ve already entered that Package." }, JsonRequestBehavior.AllowGet);
            }
            var resCreate = productPackageRepository.Create(data);
            return Json(new { resCreate.status, resCreate.message }, JsonRequestBehavior.AllowGet);
        }
        // POST: ProductPackage/Edit/5
        [Route("ProductPackage/Edit")]
        [HttpPost]
        public JsonResult Edit(tbl_products_Package data)
        {

            var productPackage = context.tbl_products_Package.FirstOrDefault(x => x.Product_PackageID == data.Product_PackageID);
            return Json(productPackage, JsonRequestBehavior.AllowGet);
        }
        public ActionResult Show(long id)
        {
            var package = context.tbl_products_Package.FirstOrDefault(x => x.Product_PackageID == id);
            ViewBag.PackageID = package.Product_PackageID;
            ViewBag.PackageName = package.Product_Package;
            DropDownListFor();
            return View();
        }
        public ActionResult GetShowForDataTable(BaseDatatable param)
        {
            //System.Diagnostics.Debug.Write("Hello " + Request["ProductID"]);
            var data = productPackageRepository.GetProductPackageForDataTable(long.Parse(Request["Product_PackageID"]));
            if (!string.IsNullOrEmpty(param.sSearch) &&
                !string.IsNullOrWhiteSpace(param.sSearch))
            {
                data = data.Where(x => x.PrdNameEng.ToLower().Contains(param.sSearch.ToLower())).ToList();
            }
            var sortColumnIndex = HttpContext.Request.QueryString["iSortCol_0"];
            var sortDirection = HttpContext.Request.QueryString["sSortDir_0"];
            data = productPackageRepository.SortByColumnWithOrder(sortColumnIndex, sortDirection, data);

            var displayResult = data.Skip(param.iDisplayStart)
                                .Take(param.iDisplayLength).ToList();
            var totalRecords = data.Count();
            return Json(new
            {
                param.sEcho,
                iTotalRecords = totalRecords,
                iTotalDisplayRecords = totalRecords,
                aaData = displayResult
            }, JsonRequestBehavior.AllowGet);
        }
        public void DropDownListFor()
        {
            var categories = context.tbl_prdcategory.ToList();
            List<SelectListItem> listCategories = new List<SelectListItem>();
            listCategories.Add(new SelectListItem { Text = "--categories--", Value = "" });
            foreach (var item in categories)
            {
                listCategories.Add(new SelectListItem { Text = item.PrdCategory, Value = item.PrdCategID });
            }
            ViewBag.Categories = listCategories;
            //ViewData["Categories"] = new SelectList(categories, "PrdCategID", "PrdCategory");

            var stockTypes = context.tblStockTypes.ToList();
            ViewBag.StockTypes = new SelectList(stockTypes, "StockID", "StockName");

            var suppliers = context.tbl_suppliers.ToList();
            ViewBag.Suppliers = new SelectList(suppliers, "SupplierID", "CompanyName");

            //var _product = _context.Products.Include(t => t.Category).Include(t => t.Supplier);
            //var products = from sp in context.tblStockTypeProducts
            //               join product in context.tbl_products on sp.ProductID equals product.ProductID
            //               join category in context.tbl_prdcategory on product.PrdCategID equals category.PrdCategID
            //               where (sp.StockID == IUser.StockID)
            var products = from product in context.tbl_products
                           join category in context.tbl_prdcategory on product.PrdCategID equals category.PrdCategID
                           select new
                           {
                               product.ProductID,
                               product.PrdNameEng,
                               product.OrderComment,
                               category.PrdCategory,
                               //sp.StockID,
                               //sp.Qty
                           };
            List<SelectListItem> listProduct = new List<SelectListItem>();
            //listProduct.Add(new SelectListItem { Text = "--select products--", Value = "" });
            //foreach (var item in products)
            //{
            //    listProduct.Add(new SelectListItem { Text = item.OrderComment == "" ? item.PrdNameEng : item.PrdNameEng + "|" + item.OrderComment, Value = item.ProductID });
            //}
            ViewBag.Products = listProduct;
            //ViewData["Products"] = new SelectList((from p in products
            //                                          select new
            //                                          {
            //                                              ProductID = p.ProductID,
            //                                              OrderComment = p.PrdNameEng + " | " + p.OrderComment// + " | " + p.Qty + " | " + p.PrdCategory
            //                                          }), "ProductID", "OrderComment", null);
        }
        // POST: ProductPackage/ScanBarcode
        //[Route("BuyProduct/ScanBarcode")]
        //[HttpPost]
        //public JsonResult ScanBarcode(tbl_products_Package_Detail data)
        //{
        //    if (data.Status == "createIme" && data.barCode == null)
        //    {
        //        return Json("The IME not null.", JsonRequestBehavior.AllowGet);
        //    }
        //    var barCode = context.tbl_products.Where(x => x.barCode == data.barCode).Count();
        //    if (barCode > 0)
        //    {
        //        return Json("Your\'ve already entered that Barcode.", JsonRequestBehavior.AllowGet);
        //    }
        //    return Json(buyProductRepository.UpdateOrCreateIme(data), JsonRequestBehavior.AllowGet);
        //}
        // POST: ProductPackage/AddItem
        [Route("ProductPackage/AddItem")]
        [HttpPost]
        public JsonResult AddItem(tbl_products_Package_Detail data)
        {
            if (data.Product_PackageDetail_ID != 0)
            {
                var resUpdate = productPackageRepository.UpdateItem(data);
                return Json(new { resUpdate.status, resUpdate.message }, JsonRequestBehavior.AllowGet);
            }
            var resCreate = productPackageRepository.CreateItem(data);
            return Json(new { resCreate.status, resCreate.message }, JsonRequestBehavior.AllowGet);
        }
        // POST: ProductPackage/EditItem/5
        [Route("ProductPackage/EditItem")]
        [HttpPost]
        public JsonResult EditItem(tbl_products_Package_Detail data)
        {

            var packageDetail = context.tbl_products_Package_Detail.FirstOrDefault(x => x.Product_PackageDetail_ID == data.Product_PackageDetail_ID);
            var product = context.tbl_products.FirstOrDefault(x => x.ProductID == packageDetail.ProductID);
            Product dataEdit = new Product();
            dataEdit.Product_PackageDetail_ID = packageDetail.Product_PackageDetail_ID;
            dataEdit.PrdCategory = product.PrdCategID;
            dataEdit.ProductID = packageDetail.ProductID;
            dataEdit.Quantity = packageDetail.Qty;
            dataEdit.SellingPriceUSD = packageDetail.SellingPriceUSD;
            dataEdit.Description = packageDetail.Description;
            return Json(dataEdit, JsonRequestBehavior.AllowGet);
        }

WebApplication/Views/ProductPackage/Partials/_CreateOrUpdate.cshtml
@model WebApplication.Models.tbl_products_Package
<div class="modal fade" id="modal-form">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h6 id="modal-title" class="modal-title text-secondary">
                    @*<i class="fa fa-plus-circle"></i>*@
                    @Resources.Buttons.Create
                </h6>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                @using (Html.BeginForm("Create", "ProductPackage", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="row">
                        <div class="col-12">
                            <div class="form-group">
                                @Html.HiddenFor(model => model.Product_PackageID, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.Label(@Resources.ProductPackage.PrdNameEng, htmlAttributes: new { @class = "control-label" })
                                @Html.EditorFor(model => model.Product_Package, new { htmlAttributes = new { @class = "form-control", @required = "required", @placeholder = @Resources.ProductPackage.PrdNameEng } })
                                @Html.ValidationMessageFor(model => model.Product_Package, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="form-group">
                                @Html.Label(@Resources.ProductPackage.Description, htmlAttributes: new { @class = "control-label" })
                                @Html.TextAreaFor(model => model.Description, new { @class = "form-control", @rows = 3, @placeholder = @Resources.ProductPackage.Description })
                                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                    <div class="row pt-2">
                        <div class="col text-right">
                            <button type="button" class="btn btn-danger btn-min mr-2" data-dismiss="modal">
                                <i class="fa fa-times-circle" aria-hidden="true"></i>
                                @Resources.Buttons.Cancel
                            </button>
                            <button type="submit" id="btnSaveOrUpdate" class="btn btn-success btn-min">
                                <i class="far fa-check-circle"></i>
                                @Resources.Buttons.Save
                            </button>
                        </div>
                    </div>
                }

            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<!-- /.modal -->

WebApplication/Views/ProductPackage/Partials/_CreateOrUpdateChild.cshtml
@model WebApplication.Models.tbl_products_Package_Detail
@using (Html.BeginForm("AddItem", "ProductPackage", FormMethod.Post))
{
    <div class="modal fade" id="modal-form">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h6 id="modal-title" class="modal-title text-secondary">
                        @*<i class="fa fa-code-branch"></i>*@
                        @Resources.Buttons.AddItem
                    </h6>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body px-5 py-4">
                    <div class="form-group row border-bottom pb-1">
                        <label for="Product_Package" class="col-md-4 col-lg-4 col-form-label">@Resources.ProductPackage.Product_Package</label>
                        <div class="col-md-8 col-lg-8 mb-1">
                            @Html.HiddenFor(model => model.Product_PackageDetail_ID, new { @class = "form-control", @Value = ViewBag.Product_PackageDetail_ID })
                            @Html.HiddenFor(model => model.Product_PackageID, new { @class = "form-control", @Value = ViewBag.PackageID })
                            @Html.TextBox("Product_Package", "", new { @class = "form-control", @Value = ViewBag.PackageName, @readonly = true, @placeholder = @Resources.ProductPackage.Product_Package })
                        </div>
                    </div>
                    @*<div class="form-group row pt-1">
                        <label for="barCode" id="labelBarCode" class="col-md-4 col-lg-4 col-form-label">ស្កេនបារកូដ</label>
                        <div class="col-md-8 col-lg-8 mb-1">
                            @Html.TextBox("barCode", "", new { @class = "form-control is-warning", @placeholder = "ស្កេនបារកូដ" })
                            <small id="validationBarcode"></small>
                        </div>
                    </div>*@
                    <div class="form-group row pt-1">
                        <label for="PrdCategID" class="col-md-4 col-lg-4 col-form-label">@Resources.ProductPackage.PrdCategory</label>
                        <div class="col-md-8 col-lg-8 mb-1">
                            @Html.DropDownList("PrdCategID", ViewBag.Categories as IEnumerable<SelectListItem>, new { @class = "form-control select2bs4", @style = "width:100%" })
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="PrdNameEng" class="col-md-4 col-lg-4 col-form-label">@Resources.ProductPackage.Product</label>
                        <div class="col-md-8 col-lg-8 mb-1">
                            @Html.DropDownListFor(model => model.ProductID, ViewBag.Products as IEnumerable<SelectListItem>, new { @class = "form-control select2bs4", @style = "width:100%" })
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="Quantity" class="col-md-4 col-lg-4 col-form-label">@Resources.ProductPackage.Quantity</label>
                        <div class="col-md-8 col-lg-8 mb-1">
                            @Html.EditorFor(model => model.Qty, new { htmlAttributes = new { @class = "form-control is-warning", @step = "0.01", @type = "Number", @placeholder = "0" } })
                            @Html.ValidationMessageFor(model => model.Qty, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="SellingPriceUSD" class="col-md-4 col-lg-4 col-form-label">@Resources.ProductPackage.SellingPriceUSD</label>
                        <div class="col-md-8 col-lg-8 mb-1">
                            @Html.EditorFor(model => model.SellingPriceUSD, new { htmlAttributes = new { @class = "form-control is-warning", @step = "0.01", @type = "Number", @placeholder = "0" } })
                            @Html.ValidationMessageFor(model => model.SellingPriceUSD, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="Descripiton" class="col-md-4 col-lg-4 col-form-label">@Resources.ProductPackage.Description</label>
                        <div class="col-md-8 col-lg-8 mb-1">
                            @Html.TextAreaFor(model => model.Description, new { @class = "form-control", @rows = 2, @placeholder = @Resources.ProductPackage.Description })
                            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group row pt-2">
                        <label for="" class="col-md-4 col-lg-4 col-form-label"></label>
                        <div class="col-md-4 col-lg-4">
                            <button type="button" class="btn btn-outline-danger btn-min" data-dismiss="modal">
                                <i class="fa fa-times-circle" aria-hidden="true"></i>
                                @Resources.Buttons.Cancel
                            </button>
                        </div>
                        <div class="col-md-4 col-lg-4">
                            <button type="submit" id="btnSaveOrUpdate" class="btn btn-outline-success btn-min float-right">
                                <i class="far fa-check-circle"></i>
                                @Resources.Buttons.Save
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}